language: php
php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
install: 
  - echo "CoreStaticUrl:http://website/" >> system/settings/system.ini
  - php yellow.php about
script: 
  - php yellow.php build test
